package com.dumensel.payment.application.dto;

/**
 * Masterpass Token Generation Response DTO
 * 
 * Confluence: Masterpass Integration - Token Response
 * 
 * These values MUST be passed to client-side MFS.purchase() call:
 * - token: Payment token from Masterpass
 * - orderNo: Order number
 * - terminalGroupId: Terminal group for POS routing
 * 
 * referenceId: Used for 3DS flows and complete payment
 */
public class MasterpassTokenResponse {

    /**
     * Masterpass payment token
     * MUST be passed to MFS.purchase(token, orderNo, terminalGroupId)
     */
    private String token;

    /**
     * Reference ID for tracking payment
     * Used in complete and 3DS flows
     */
    private String referenceId;

    /**
     * Order number generated by Masterpass
     */
    private String orderNo;

    /**
     * Terminal group ID for POS routing
     */
    private String terminalGroupId;

    /**
     * Conversation ID (echo back from request)
     */
    private String conversationId;

    // Constructor
    public MasterpassTokenResponse() {
    }

    public MasterpassTokenResponse(String token, String referenceId, String orderNo, 
                                   String terminalGroupId, String conversationId) {
        this.token = token;
        this.referenceId = referenceId;
        this.orderNo = orderNo;
        this.terminalGroupId = terminalGroupId;
        this.conversationId = conversationId;
    }

    // Getters and Setters
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getReferenceId() {
        return referenceId;
    }

    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getTerminalGroupId() {
        return terminalGroupId;
    }

    public void setTerminalGroupId(String terminalGroupId) {
        this.terminalGroupId = terminalGroupId;
    }

    public String getConversationId() {
        return conversationId;
    }

    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }
}
